//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameTemplate {
    
    
    public sealed class ScreenIds {
        
        public const string UIGameplay = "UIGameplay";
        
        public const string UILoading = "UILoading";
        
        public const string UILose = "UILose";
        
        public const string UIMain = "UIMain";
        
        public const string UIWin = "UIWin";
    }
}
